name: Automated Tests

on: pull_request

jobs:
  jest:
    name: jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
        with:
          node-version: 20.17.0

      - run: npm ci

      - run: npm test
